[package]
name = "py-rs-interop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_rs_interop"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
